name: Docker Test
on: push

jobs:
  test-docker:
    runs-on: ubuntu-latest
    services:
      customMySql:
        image: mysql
    container:
      image: node:23-alpine3.19
      env:
        NODE_ENV: development
      ports:
        - 80
    steps:
      - name: Display service image
        run: echo '${{ toJSON(job.services) }}'
      - name: Display node version
        run: |
          node -v
          cat /etc/os-release
      - name: Print new node version
        uses: docker://node:20-bookworm
        with:
          args: -v