name: Eigth Workflow
on: 
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Type the Title
        type: string
        required: true
        default: Hello World!
      selectCustom:
        description: custom comboBox
        type: choice
        required: true
        options:
          - Value 1
          - Value 2
          - Value 3
        default: 
          Value 2
      checkCustom:
        description: Custom CheckBox
        type: boolean
        required: false

jobs: 
  echo-vars:
    runs-on: macos-latest
    steps:
      - run: |
         echo $GITHUB_SHA
         echo $GITHUB_REF
         echo "Title is ${{ inputs.titleCustom }}"
         echo "Title is ${{ inputs.selectCustom }}"
         echo "Title is ${{ inputs.checkCustom }}"
  
  