name: Eleventh Workflow
on: 
  push
env:
  WF_CUSTOM_VAR: WF 1
run-name: Echo vars

jobs: 
  echo-vars:
    env:
      JOB_CUSTOM_VAR: JOB 1
    runs-on: ubuntu-latest
    steps:
      - name: Create variable
        env: 
          NEW_CUSTOM_VAR1: VAR 1
        run: |
          echo "NEW_CUSTOM_VAR2=VAR 2" >> "GITHUB_ENV"
          echo $NEW_CUSTOM_VAR1 >> "GITHUB_ENV"
      - name: Vars
        env:
          STEP_CUSTOM_VAR: STEP 1
          WF_CUSTOM_VAR: WF 1 - STEP 1
        run: |
         echo $GITHUB_REF
         echo ${{github.ref}}
         echo $WF_CUSTOM_VAR
         echo ${{ env.WF_CUSTOM_VAR}}
         echo ${{ env.JOB_CUSTOM_VAR}}
         echo ${{ env.STEP_CUSTOM_VAR}}
         echo $NEW_CUSTOM_VAR1
         echo $NEW_CUSTOM_VAR2
  
  