name: Fifteenth Workflow
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Math expression
        run: expr 2 + 2 > math.txt
      - name: upload result
        uses: actions/upload-artifact@v3
        with:
          name: math
          path: math.txt
  another-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with: 
          name: math
      - name: Mdify result
        run: |
          value=`cat math.txt`
          echo $expr value \* 3 > math.txt
          - name: upload result
          uses: actions/upload-artifact@v3
          with:
            name: math
            path: math.txt

  second-job:
    runs-on: ubuntu-latest
    needs: another-job
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with: 
          name: math
      - name: Display result
        run: |
          value=`cat math.txt`
          echo $value