name: Fifteenth Workflow
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Math expression
        run: expr 2+2 > math.txt
      - name: upload result
        uses: actions/upload-artifact@v3
        with:
          name: math
          path: math.txt
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: DOwnload artifact
        uses: actions/download-artifact@v3
        with: 
          name: math
      - name: Display result
        run: |
          value=`cat math.txt`
          echo $value