name: Fourteenth Workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        id: cache-step
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: "cache-files"
      - name: Display cache
        run: echo ${{ toJson(steps.cache-step.outputs) }}
      - name: Install node modules
        run: npm install

