name: Fourteenth Workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        id: cache-step
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cache-files-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-files-
            ${{ runner.os }}
      - name: Display cache
        run: echo '${{ toJSON(steps.cache-step.outputs) }}'
      - name: Install node modules
        run: npm install

