name: Sixteenth Workflow
run-name: Display context info
on: push

jobs:
    test-node:
      strategy:
        matrix:
          node-version: [12,14,17]
      runs-on: ubuntu-latest
      steps:
        - run: node -v
        - uses: actions/setup-node@v3
          with: 
            node-version: ${{ matrix.node-version}}
        - run: node -v
          