name: Sixteenth Workflow
run-name: Display noode version - matrix
on: push

jobs:
    test-node:
      strategy:
        matrix:
          os: [ubuntu-latest, windows-2022]
          node-version: [12,14,17]
          include:
            - os: macos-latest
              node-version: 15
          exclude:
            - os: ubuntu-latest
              node-version: 14
        fail-fast: false
        max-parallel: 2
      runs-on: ${{ matrix.os }}
      steps:
        - run: node -v
        - uses: actions/setup-node@v3
          with: 
            node-version: ${{ matrix.node-version}}
        - run: node -v
          