name: Tenth Workflow
on: 
  push
run-name: Display context info

jobs: 
  echo-vars:
    runs-on: macos-latest
    steps:
      - name: Context and Expressions
        id: context-expression
        run: |
         echo '${{ toJson(github) }}'
         echo '${{ toJson(runner) }}'
         echo '${{ toJson(job) }}'
      - name: Steps
        id: steps
        run: |
         echo '${{ toJson(steps) }}'
  
  