name: Tenth Workflow
on: 
  push

jobs: 
  echo-vars:
    runs-on: macos-latest
    steps:
      - name: Context and Expressions
        id: context-expression
        run: |
         echo ${{ toJson(github) }}
         echo ${{ toJson(runner) }}
         echo ${{ toJson(job) }}
         echo ${{ toJson(steps) }}
  
  