name: Thirteenth Workflow
on:
  push

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: exit 1
      - name: Runs On Cancelled
        if: ${{ cancelled() }} 
        run: echo "Runs On Cancelled"
      - name: Runs On Success
        if: ${{ Success() }} 
        run: echo "Runs On Success"
      - name: Runs anyway
        if: ${{ always() }} 
        run: echo "Runs anyway"
      - name: Runs On Failure
        if: ${{ failure() }} 
        run: echo "Runs On Failure"
  second-job:
    runs-on: ubuntu-latest
    needs: job
    if: ${{ failure() }}
    steps:
      - name: Step
        run: echo 'Job was failed'
