name: Third Workflow
on: [push]

jobs: 
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List files before copy
        run: ls -a
      - uses: actions/checkout@v4
      - name: List files after copy
        run: ls -a
  