name: concurrency test
on: workflow_dispatch
concurrency: 
  group: concurrency-test
  cancel-in-progress: true

jobs:
  test-timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: sleep 200