name: Twelveth Workflow
on: 
  push
run-name: Echo repository secrets and vars

jobs: 
  echo-vars:
    runs-on: ubuntu-latest
    environment: "staging"
    steps:
      - name: Vars
        run: |
         echo ${{vars.STATUS}}
         echo ${{secrets.PASSWORD}}
  
  